import type { DslSceneInput, MetadataSpec, SceneSpec } from '@tussel/dsl';
import type { PatternBuilder, SignalBuilder } from './index.js';

declare global {
  interface String {
    add(value: unknown): PatternBuilder;
    almostAlways(value: unknown): PatternBuilder;
    almostNever(value: unknown): PatternBuilder;
    compress(begin: unknown, end: unknown): PatternBuilder;
    contract(value: unknown): PatternBuilder;
    degrade(): PatternBuilder;
    degradeBy(value: unknown): PatternBuilder;
    div(value: unknown): PatternBuilder;
    drop(value: unknown): PatternBuilder;
    every(value: unknown, transform: unknown): PatternBuilder;
    early(value: unknown): PatternBuilder;
    expand(value: unknown): PatternBuilder;
    extend(value: unknown): PatternBuilder;
    fast(value: unknown): PatternBuilder;
    fastGap(value: unknown): PatternBuilder;
    grow(value: unknown): PatternBuilder;
    hurry(value: unknown): PatternBuilder;
    jux(transform: unknown): PatternBuilder;
    juxBy(value: unknown, transform: unknown): PatternBuilder;
    late(value: unknown): PatternBuilder;
    layer(...transforms: unknown[]): PatternBuilder;
    linger(value: unknown): PatternBuilder;
    log(): string;
    loop(value?: unknown): PatternBuilder;
    midichan(value: unknown): PatternBuilder;
    midicc(value: unknown): PatternBuilder;
    midiport(value: unknown): PatternBuilder;
    midivalue(value: unknown): PatternBuilder;
    mul(value: unknown): PatternBuilder;
    off(time: unknown, transform: unknown): PatternBuilder;
    often(transform: unknown): PatternBuilder;
    osc(value: unknown): PatternBuilder;
    oschost(value: unknown): PatternBuilder;
    oscport(value: unknown): PatternBuilder;
    pace(value: unknown): PatternBuilder;
    ply(value: unknown): PatternBuilder;
    rarely(transform?: unknown): PatternBuilder;
    rev(): PatternBuilder;
    rootNotes(value?: unknown): PatternBuilder;
    scramble(value: unknown): PatternBuilder;
    scale(value: unknown): PatternBuilder;
    scaleTranspose(value: unknown): PatternBuilder;
    shuffle(value: unknown): PatternBuilder;
    shrink(value: unknown): PatternBuilder;
    slow(value: unknown): PatternBuilder;
    slowGap(value: unknown): PatternBuilder;
    sometimes(transform: unknown): PatternBuilder;
    sometimesBy(value: unknown, transform: unknown): PatternBuilder;
    sub(value: unknown): PatternBuilder;
    superimpose(...transforms: unknown[]): PatternBuilder;
    take(value: unknown): PatternBuilder;
    tour(...values: unknown[]): PatternBuilder;
    transpose(value: unknown): PatternBuilder;
    velocity(value: unknown): PatternBuilder;
    voicings(value: unknown): PatternBuilder;
    when(value: unknown, transform: unknown): PatternBuilder;
    within(begin: unknown, end: unknown, transform: unknown): PatternBuilder;
    zoom(begin: unknown, end: unknown): PatternBuilder;
  }

  const cat: typeof import('./index.js').cat;
  const add: typeof import('./index.js').add;
  const cc: typeof import('./index.js').cc;
  const choose: typeof import('./index.js').choose;
  const areStringPrototypeExtensionsInstalled: typeof import('./index.js').areStringPrototypeExtensionsInstalled;
  const chord: typeof import('./index.js').chord;
  const clearHydra: typeof import('./index.js').clearHydra;
  const compress: typeof import('./index.js').compress;
  const contract: typeof import('./index.js').contract;
  const cosine: SignalBuilder;
  const csound: typeof import('./index.js').csound;
  const csoundm: typeof import('./index.js').csoundm;
  const createParam: typeof import('./index.js').createParam;
  const createParams: typeof import('./index.js').createParams;
  const defineScene: typeof import('./index.js').defineScene;
  const div: typeof import('./index.js').div;
  const drop: typeof import('./index.js').drop;
  const early: typeof import('./index.js').early;
  const expand: typeof import('./index.js').expand;
  const extend: typeof import('./index.js').extend;
  const fast: typeof import('./index.js').fast;
  const fastGap: typeof import('./index.js').fastGap;
  const gamepad: typeof import('./index.js').gamepad;
  const grow: typeof import('./index.js').grow;
  const H: typeof import('./index.js').H;
  const hydra: typeof import('./index.js').hydra;
  const hurry: typeof import('./index.js').hurry;
  const installStringPrototypeExtensions: typeof import('./index.js').installStringPrototypeExtensions;
  const initHydra: typeof import('./index.js').initHydra;
  const input: typeof import('./index.js').input;
  const late: typeof import('./index.js').late;
  const linger: typeof import('./index.js').linger;
  const loadCSound: typeof import('./index.js').loadCSound;
  const loadCsound: typeof import('./index.js').loadCsound;
  const loadOrc: typeof import('./index.js').loadOrc;
  const loadcsound: typeof import('./index.js').loadcsound;
  const m: typeof import('./index.js').m;
  const mini: typeof import('./index.js').mini;
  const mondo: typeof import('./index.js').mondo;
  const motion: typeof import('./index.js').motion;
  const mul: typeof import('./index.js').mul;
  const n: typeof import('./index.js').n;
  const note: typeof import('./index.js').note;
  const pace: typeof import('./index.js').pace;
  const perlin: SignalBuilder;
  const ply: typeof import('./index.js').ply;
  const polymeter: typeof import('./index.js').polymeter;
  const polyrhythm: typeof import('./index.js').polyrhythm;
  const rand: SignalBuilder;
  const rev: typeof import('./index.js').rev;
  const s: typeof import('./index.js').s;
  const scramble: typeof import('./index.js').scramble;
  const samples: typeof import('./index.js').samples;
  const saw: SignalBuilder;
  const scene: <TScene extends DslSceneInput>(input: TScene) => TScene;
  const seq: typeof import('./index.js').seq;
  const setGamepadValue: typeof import('./index.js').setGamepadValue;
  const setInputValue: typeof import('./index.js').setInputValue;
  const setMidiValue: typeof import('./index.js').setMidiValue;
  const setMotionValue: typeof import('./index.js').setMotionValue;
  const setbpm: typeof import('./index.js').setbpm;
  const setcpm: typeof import('./index.js').setcpm;
  const setcps: typeof import('./index.js').setcps;
  const shuffle: typeof import('./index.js').shuffle;
  const sine: SignalBuilder;
  const silence: typeof import('./index.js').silence;
  const slow: typeof import('./index.js').slow;
  const slowGap: typeof import('./index.js').slowGap;
  const sound: typeof import('./index.js').sound;
  const square: SignalBuilder;
  const stack: typeof import('./index.js').stack;
  const stepalt: typeof import('./index.js').stepalt;
  const stepcat: typeof import('./index.js').stepcat;
  const zip: typeof import('./index.js').zip;
  const shrink: typeof import('./index.js').shrink;
  const sub: typeof import('./index.js').sub;
  const take: typeof import('./index.js').take;
  const tri: SignalBuilder;
  const triangle: SignalBuilder;
  const uninstallStringPrototypeExtensions: typeof import('./index.js').uninstallStringPrototypeExtensions;
  const value: typeof import('./index.js').value;
  const wchoose: typeof import('./index.js').wchoose;
  const sequence: typeof import('./index.js').sequence;
  const zoom: typeof import('./index.js').zoom;
  const midi: typeof import('./index.js').midi;
}

export type { DslSceneInput, MetadataSpec, PatternBuilder, SceneSpec, SignalBuilder };
