import type { MetadataSpec, SceneInput, SceneSpec } from '@tussel/dsl';
import type { PatternBuilder, SignalBuilder } from './index';

declare global {
  interface String {
    add(value: unknown): PatternBuilder;
    almostAlways(value: unknown): PatternBuilder;
    almostNever(value: unknown): PatternBuilder;
    compress(begin: unknown, end: unknown): PatternBuilder;
    contract(value: unknown): PatternBuilder;
    degrade(): PatternBuilder;
    degradeBy(value: unknown): PatternBuilder;
    div(value: unknown): PatternBuilder;
    drop(value: unknown): PatternBuilder;
    every(value: unknown, transform: unknown): PatternBuilder;
    early(value: unknown): PatternBuilder;
    expand(value: unknown): PatternBuilder;
    extend(value: unknown): PatternBuilder;
    fast(value: unknown): PatternBuilder;
    fastGap(value: unknown): PatternBuilder;
    grow(value: unknown): PatternBuilder;
    hurry(value: unknown): PatternBuilder;
    jux(transform: unknown): PatternBuilder;
    juxBy(value: unknown, transform: unknown): PatternBuilder;
    late(value: unknown): PatternBuilder;
    layer(...transforms: unknown[]): PatternBuilder;
    linger(value: unknown): PatternBuilder;
    log(): string;
    loop(value?: unknown): PatternBuilder;
    midichan(value: unknown): PatternBuilder;
    midicc(value: unknown): PatternBuilder;
    midiport(value: unknown): PatternBuilder;
    midivalue(value: unknown): PatternBuilder;
    mul(value: unknown): PatternBuilder;
    off(time: unknown, transform: unknown): PatternBuilder;
    often(transform: unknown): PatternBuilder;
    osc(value: unknown): PatternBuilder;
    oschost(value: unknown): PatternBuilder;
    oscport(value: unknown): PatternBuilder;
    pace(value: unknown): PatternBuilder;
    ply(value: unknown): PatternBuilder;
    rarely(transform?: unknown): PatternBuilder;
    rev(): PatternBuilder;
    rootNotes(value?: unknown): PatternBuilder;
    scramble(value: unknown): PatternBuilder;
    scale(value: unknown): PatternBuilder;
    scaleTranspose(value: unknown): PatternBuilder;
    shuffle(value: unknown): PatternBuilder;
    shrink(value: unknown): PatternBuilder;
    slow(value: unknown): PatternBuilder;
    slowGap(value: unknown): PatternBuilder;
    sometimes(transform: unknown): PatternBuilder;
    sometimesBy(value: unknown, transform: unknown): PatternBuilder;
    sub(value: unknown): PatternBuilder;
    superimpose(...transforms: unknown[]): PatternBuilder;
    take(value: unknown): PatternBuilder;
    tour(...values: unknown[]): PatternBuilder;
    transpose(value: unknown): PatternBuilder;
    velocity(value: unknown): PatternBuilder;
    voicings(value: unknown): PatternBuilder;
    when(value: unknown, transform: unknown): PatternBuilder;
    within(begin: unknown, end: unknown, transform: unknown): PatternBuilder;
    zoom(begin: unknown, end: unknown): PatternBuilder;
  }

  const cat: typeof import('./index').cat;
  const add: typeof import('./index').add;
  const cc: typeof import('./index').cc;
  const choose: typeof import('./index').choose;
  const areStringPrototypeExtensionsInstalled: typeof import('./index').areStringPrototypeExtensionsInstalled;
  const chord: typeof import('./index').chord;
  const clearHydra: typeof import('./index').clearHydra;
  const compress: typeof import('./index').compress;
  const contract: typeof import('./index').contract;
  const cosine: SignalBuilder;
  const csound: typeof import('./index').csound;
  const csoundm: typeof import('./index').csoundm;
  const createParam: typeof import('./index').createParam;
  const createParams: typeof import('./index').createParams;
  const defineScene: typeof import('./index').defineScene;
  const div: typeof import('./index').div;
  const drop: typeof import('./index').drop;
  const early: typeof import('./index').early;
  const expand: typeof import('./index').expand;
  const extend: typeof import('./index').extend;
  const fast: typeof import('./index').fast;
  const fastGap: typeof import('./index').fastGap;
  const gamepad: typeof import('./index').gamepad;
  const grow: typeof import('./index').grow;
  const H: typeof import('./index').H;
  const hydra: typeof import('./index').hydra;
  const hurry: typeof import('./index').hurry;
  const installStringPrototypeExtensions: typeof import('./index').installStringPrototypeExtensions;
  const initHydra: typeof import('./index').initHydra;
  const input: typeof import('./index').input;
  const late: typeof import('./index').late;
  const linger: typeof import('./index').linger;
  const loadCSound: typeof import('./index').loadCSound;
  const loadCsound: typeof import('./index').loadCsound;
  const loadOrc: typeof import('./index').loadOrc;
  const loadcsound: typeof import('./index').loadcsound;
  const m: typeof import('./index').m;
  const mini: typeof import('./index').mini;
  const mondo: typeof import('./index').mondo;
  const motion: typeof import('./index').motion;
  const mul: typeof import('./index').mul;
  const n: typeof import('./index').n;
  const note: typeof import('./index').note;
  const pace: typeof import('./index').pace;
  const perlin: SignalBuilder;
  const ply: typeof import('./index').ply;
  const polymeter: typeof import('./index').polymeter;
  const polyrhythm: typeof import('./index').polyrhythm;
  const rand: SignalBuilder;
  const rev: typeof import('./index').rev;
  const s: typeof import('./index').s;
  const scramble: typeof import('./index').scramble;
  const samples: typeof import('./index').samples;
  const saw: SignalBuilder;
  const scene: <TScene extends SceneInput>(input: TScene) => TScene;
  const seq: typeof import('./index').seq;
  const setGamepadValue: typeof import('./index').setGamepadValue;
  const setInputValue: typeof import('./index').setInputValue;
  const setMidiValue: typeof import('./index').setMidiValue;
  const setMotionValue: typeof import('./index').setMotionValue;
  const setbpm: typeof import('./index').setbpm;
  const setcpm: typeof import('./index').setcpm;
  const setcps: typeof import('./index').setcps;
  const shuffle: typeof import('./index').shuffle;
  const sine: SignalBuilder;
  const silence: typeof import('./index').silence;
  const slow: typeof import('./index').slow;
  const slowGap: typeof import('./index').slowGap;
  const sound: typeof import('./index').sound;
  const square: SignalBuilder;
  const stack: typeof import('./index').stack;
  const stepalt: typeof import('./index').stepalt;
  const stepcat: typeof import('./index').stepcat;
  const zip: typeof import('./index').zip;
  const shrink: typeof import('./index').shrink;
  const sub: typeof import('./index').sub;
  const take: typeof import('./index').take;
  const tri: SignalBuilder;
  const triangle: SignalBuilder;
  const uninstallStringPrototypeExtensions: typeof import('./index').uninstallStringPrototypeExtensions;
  const value: typeof import('./index').value;
  const wchoose: typeof import('./index').wchoose;
  const sequence: typeof import('./index').sequence;
  const zoom: typeof import('./index').zoom;
  const midi: typeof import('./index').midi;
}

export type { MetadataSpec, PatternBuilder, SceneInput, SceneSpec, SignalBuilder };
